# Generated by Django 6.0 on 2025-12-21 22:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video1', models.FileField(upload_to='videos/')),
                ('video2', models.FileField(upload_to='videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_json', models.FileField(blank=True, null=True, upload_to='results/')),
                ('result_csv', models.FileField(blank=True, null=True, upload_to='results/')),
                ('landmark_csv', models.FileField(blank=True, null=True, upload_to='results/')),
                ('joint_csv', models.FileField(blank=True, null=True, upload_to='results/')),
                ('summary_txt', models.FileField(blank=True, null=True, upload_to='results/')),
                ('comparison_video', models.FileField(blank=True, null=True, upload_to='results/')),
                ('avg_position_diff', models.FloatField(blank=True, null=True)),
                ('avg_angle_diff', models.FloatField(blank=True, null=True)),
                ('dtw_position_distance', models.FloatField(blank=True, null=True)),
                ('dtw_angle_distance', models.FloatField(blank=True, null=True)),
                ('total_aligned_pairs', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
